Repository bbaegi-six/dondothat-server, pull requests merged in 2025-07, with the labels that each got.

#6 [FIX] deploy시 deploy.sh 스크립트를 인스턴스로 함께 전송
  .github/workflows/ci-cd.yml
Labels: bug

#7 [FIX] deploy.sh 파일이 GitHub Actions 러너에 존재하는지 확인하는 디버깅 단계 추가
  .github/workflows/ci-cd.yml
Labels: bug

#8 [FIX] deploy 잡에 actions/checkout@v3 스텝을 추가
  .github/workflows/ci-cd.yml
Labels: bug

#12 [BUG] WAR 파일을 찾을 수 없는 문제
  .github/workflows/ci-cd.yml
Labels: bug

#16 [BUG] Transfer build/libs directory and remove redundant verification
  .github/workflows/ci-cd.yml
Labels: bug

#20 [FIX] Resolve heredoc syntax error in deploy.sh 2
  deploy.sh
Labels: fix

#21 [FIX] Check webapps directory
  deploy.sh
Labels: fix

#23 [Fix] Add database source in properties
  src/main/resources/application.properties
Labels: fix

#24 [FIX] Rebuild WAR file
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/resources/main/application.properties
Labels: fix

#38 [FIX] 카테고리, 리워드 패키지 추가. 매퍼 인터페이스 연결 완료
  src/main/java/org/bbagisix/category/controller/CategoryController.java
  src/main/java/org/bbagisix/category/domain/CategoryVO.java
  src/main/java/org/bbagisix/category/dto/CategoryDTO.java
  src/main/java/org/bbagisix/category/mapper/CategoryMapper.java
  src/main/java/org/bbagisix/category/service/CategoryService.java
  src/main/java/org/bbagisix/reward/controller/RewardController.java
  src/main/java/org/bbagisix/reward/domain/RewardVO.java
  src/main/java/org/bbagisix/reward/dto/RewardDTO.java
  src/main/java/org/bbagisix/reward/mapper/RewardMapper.java
  src/main/java/org/bbagisix/reward/service/RewardService.java
  src/main/resources/mappers/category/CategoryMapper.xml
  src/main/resources/mappers/reward/RewardMapper.xml
Labels: 🔧fix

#48 [FIX] develop 브랜치에 ci 파이프라인 추가
  .github/workflows/ci-cd.yml
Labels: 🔧fix

#52 Fix/50
  llm-server/server.py
Labels: 🔧fix

#68 [FEAT] llm-server 도커 이미지 빌드 단계 추가
  .github/workflows/ci-cd.yml
Labels: ✨feat

#85 [FIX] mybatis-config 수정
  src/main/resources/mybatis-config.xml
Labels: 🐞bugfix

#93 [FEAT] 카테고리 분류에 키워드 필터링 과정 추가 #92
  llm-server/server.py
Labels: ✨feat

#95 [FIX] 프론트엔드 연동을 위한 CORS 설정 추가 #90
  src/main/java/org/bbagisix/config/ServletConfig.java
  src/main/java/org/bbagisix/expense/dto/ExpenseDTO.java
Labels: 🐞bugfix

#97 [FIX] SecurityConfig에 CORS 설정 추가
  src/main/java/org/bbagisix/config/ServletConfig.java
  src/main/java/org/bbagisix/oauth2/config/SecurityConfig.java
Labels: 🐞bugfix
