Repository bbaegi-six/dondothat-server, pull requests merged in 2025-08, with the labels that each got.

#98 [FEAT] 소셜 로그인 성공 시 JWT 발급
  .github/workflows/ci-cd.yml
  docker-compose.yml
  src/main/java/org/bbagisix/config/RootConfig.java
  src/main/java/org/bbagisix/config/SecurityConfig.java
  src/main/java/org/bbagisix/config/WebConfig.java
  src/main/java/org/bbagisix/oauth2/dto/UserDTO.java
  src/main/java/org/bbagisix/user/controller/OAuth2Controller.java
  src/main/java/org/bbagisix/user/controller/UserController.java
  src/main/java/org/bbagisix/user/domain/UserVO.java
  src/main/java/org/bbagisix/user/dto/CustomOAuth2User.java
  src/main/java/org/bbagisix/user/dto/GoogleResponse.java
  src/main/java/org/bbagisix/user/dto/GoogleTokenResponse.java
  src/main/java/org/bbagisix/user/dto/NaverResponse.java
  src/main/java/org/bbagisix/user/dto/OAuth2Response.java
  src/main/java/org/bbagisix/user/dto/UserDTO.java
  src/main/java/org/bbagisix/user/dto/UserResponse.java
  src/main/java/org/bbagisix/user/filter/JWTFilter.java
  src/main/java/org/bbagisix/user/handler/CustomOAuth2SuccessHandler.java
  src/main/java/org/bbagisix/user/mapper/UserMapper.java
  src/main/java/org/bbagisix/user/service/CustomOAuth2UserService.java
  src/main/java/org/bbagisix/user/service/OAuth2Service.java
  src/main/java/org/bbagisix/user/service/OAuth2ServiceImpl.java
  src/main/java/org/bbagisix/user/service/UserService.java
  src/main/java/org/bbagisix/user/util/JwtUtil.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨feat

#123 [FEAT] 저금통 API 구현
  src/main/java/org/bbagisix/asset/controller/AssetController.java
  src/main/java/org/bbagisix/codef/service/CodefSchedulerService.java
  src/main/java/org/bbagisix/saving/controller/SavingController.java
  src/main/java/org/bbagisix/saving/domain/UserChallengeVO.java
  src/main/java/org/bbagisix/saving/dto/SavingDTO.java
  src/main/java/org/bbagisix/saving/mapper/SavingMapper.java
  src/main/java/org/bbagisix/saving/service/SavingService.java
  src/main/resources/mappers/saving/SavingMapper.xml
Labels: ✨feat

#133 [FEAT] 카테고리 분류 연결작업
  src/main/java/org/bbagisix/analytics/service/AnalyticsServiceImpl.java
  src/main/java/org/bbagisix/classify/service/ClassifyServiceImpl.java
Labels: ✨feat

#134 [FIX] 카테고리 아이디 안바뀌는 문제 #127
  src/main/java/org/bbagisix/classify/service/ClassifyServiceImpl.java
Labels: 🐞bugfix

#138 [FEAT] 챌린지 추천
  src/main/java/org/bbagisix/challenge/controller/ChallengeController.java
  src/main/java/org/bbagisix/challenge/mapper/ChallengeMapper.java
  src/main/java/org/bbagisix/challenge/service/ChallengeService.java
  src/main/resources/mappers/challenge/ChallengeMapper.xml
Labels: ✨feat

#150 [BUG] build.gradle 파일 수정
  build.gradle
Labels: 🐞bugfix

#158 [FIX] is_active 초깃값 1로 변경
  src/main/resources/mappers/challenge/ChallengeMapper.xml
Labels: 🔧refactor

#165 [FIX] 배포 환경에서 codef scheduler 중지
  src/main/java/org/bbagisix/config/RootConfig.java
Labels: 🐞bugfix

#180 [REFACTOR] 내역 페이지에서 main (주거래) 계좌만 출력하도록 수정.
  src/main/resources/mappers/expense/ExpenseMapper.xml
Labels: 🔧refactor

#183 [BUG] 지출 내역 생성/수정 기능 오류 수정
  src/main/java/org/bbagisix/expense/controller/ExpenseController.java
  src/main/java/org/bbagisix/expense/service/ExpenseServiceImpl.java
Labels: 🐞bugfix

#186 [REFACTOR] 챌린지 참여 API 수정
  src/main/resources/mappers/challenge/ChallengeMapper.xml
Labels: 🔧refactor

#191 [FEAT] 이전 챌린지 목록(성공실패) api 구현
  src/main/java/org/bbagisix/challenge/mapper/ChallengeMapper.java
  src/main/java/org/bbagisix/mypage/controller/MyPageController.java
  src/main/java/org/bbagisix/mypage/domain/UserChallengeDTO.java
  src/main/java/org/bbagisix/mypage/service/MyPageService.java
  src/main/resources/mappers/challenge/ChallengeMapper.xml
Labels: ✨feat

#192 [FEAT] 마이페이지 티어 API
  src/main/java/org/bbagisix/challenge/service/ChallengeService.java
  src/main/java/org/bbagisix/mypage/controller/MyPageController.java
  src/main/java/org/bbagisix/mypage/domain/MyPageDTO.java
  src/main/java/org/bbagisix/mypage/service/MyPageService.java
  src/main/java/org/bbagisix/tier/controller/TierController.java
  src/main/java/org/bbagisix/tier/service/TierService.java
  src/main/java/org/bbagisix/user/dto/UserResponse.java
  src/main/java/org/bbagisix/user/mapper/UserMapper.java
  src/main/java/org/bbagisix/user/service/UserService.java
  src/main/resources/mappers/tier/TierMapper.xml
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨feat

#194 [FEAT] close API 추가 #193
  src/main/java/org/bbagisix/challenge/controller/ChallengeController.java
  src/main/java/org/bbagisix/challenge/service/ChallengeService.java
  src/main/java/org/bbagisix/exception/ErrorCode.java
Labels: ✨feat

#196 [FEAT] 챌린지 실패시 소비내역 호출 api 구현
  src/main/java/org/bbagisix/challenge/controller/ChallengeController.java
  src/main/java/org/bbagisix/challenge/dto/ChallengeFailDTO.java
  src/main/java/org/bbagisix/challenge/mapper/ChallengeMapper.java
  src/main/java/org/bbagisix/challenge/service/ChallengeService.java
  src/main/resources/mappers/challenge/ChallengeMapper.xml
Labels: ✨feat

#208 [REFACTOR] LLM 성능개선
  llm-server/server.py
Labels: 🔧refactor

#212 [FIX] 배포 환경에서 채팅 연결 안됨
  nginx/nginx.conf
Labels: 🐞bugfix, ✨feat

#218 [FIX] 챌린지 실패 시 결제 내역 조회 쿼리 수정
  src/main/resources/mappers/challenge/ChallengeMapper.xml
Labels: 🐞bugfix
